AcunMedyaPortfolyoProject/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaPortfolyoProject.Controllers
{
    public class AdminLayoutController : Controller
    {
        // GET: AdminLayout
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {
            return PartialView();
        }

        public PartialViewResult PartialMenu()
        {
            return PartialView();
        }
        public PartialViewResult PartialScript()
        {
            return PartialView();
        }

    }
}

AcunMedyaPortfolyoProject/Views/AdminLayout/Index.cshtml
@{
    Layout = null; 
}
<!doctype html>
<html lang="en">
@Html.Action("PartialHead", "AdminLayout")
<body>

    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar" class="active">
            <div class="custom-menu">
                <button type="button" id="sidebarCollapse" class="btn btn-primary">
                    <i class="fa fa-bars"></i>
                    <span class="sr-only">Toggle Menu</span>
                </button>
            </div>
            <div class="p-4">
                <h1><a href="index.html" class="logo">Flash</a></h1>

                @Html.Action("PartialMenu", "AdminLayout")
                <div class="mb-5">
                    <h3 class="h6 mb-3"></h3>
                    <form action="#" class="subscribe-form">
                        <div class="form-group d-flex">
                            <div class="icon"><span class="icon-paper-plane"></span></div>
                            <input type="text" class="form-control" placeholder="Enter Email Address">
                        </div>
                    </form>
                </div>

                <div class="footer">
                <p>
                  
                 &copy;
            <script>document.write(new Date().getFullYear());</script>  <i class="icon-heart" aria-hidden="true"></i>  <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
                 
                </p>
            </div>

            </div>
        </nav>
    
        <!-- Page Content  -->


        <div id="content" class="p-4 p-md-5 pt-5">

            @RenderBody()

        </div>

        @Html.Action("PartialScript", "AdminLayout")
</body>

AcunMedyaPortfolyoProject/Views/AdminLayout/PartialHead.cshtml
<head>
    <title>Sidebar 03</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/sidebar-03/css/style.css" rel="stylesheet" />
</head>

AcunMedyaPortfolyoProject/Views/AdminLayout/PartialMenu.cshtml
<ul class="list-unstyled components mb-5">
    <li class="active">
        <a href="/Statistik"><span class="fa fa-home mr-3"></span> Dashboard</a>
    </li>
    <li>
        <a href="/Categories"><span class="fa fa-th-list mr-3"></span> Kategoriler</a>
    </li>
    <li>
        <a href="/About"><span class="fa fa-info-circle mr-3"></span> Hakkımızda</a>
    </li>
    <li>
        <a href="/Education"><span class="fa fa-graduation-cap mr-3"></span> Eğitim</a>
    </li>
    <li>
        <a href="/Jobs"><span class="fa  fa-briefcase mr-3"></span> İş</a>
    </li>
    <li>
        <a href="/Message"><span class="fa fa-envelope mr-3"></span> Mesajlar</a>
    </li>
    <li>
        <a href="/Project"><span class="fa fa-folder-open mr-3"></span> Projeler</a>
    </li>
    <li>
        <a href="/Services"><span class="fa  fa-cogs mr-3"></span> Hizmetler</a>
    </li>
    <li>
        <a href="/Skill"><span class="fa fa-user mr-3"></span> Yetenekler</a>
    </li>
    <li>
        <a href="/Slider"><span class="fa fa-user mr-3"></span> Slider</a>
    </li>
    <li>
        <a href="/Testimonial"><span class="fa fa-users mr-3"></span> Referanslar</a>
    </li>
    <li>
        <a href="/GoToPage"><span class="fa  fa-paper-plane mr-3"></span> Sayfaya Git</a>
    </li>
    <li>

        <a href="/Contact"><span class="fa fa-paper-plane mr-3"></span> Contact</a>
    </li>
</ul>

AcunMedyaPortfolyoProject/Views/AdminLayout/PartialScript.cshtml
<script src="~/sidebar-03/js/jquery.min.js"></script>
<script src="~/sidebar-03/js/popper.js"></script>
<script src="~/sidebar-03/js/bootstrap.min.js"></script>
<script src="~/sidebar-03/js/main.js"></script>